### PR TITLE
Radio List Enhancements

### PR DESCRIPTION
**Pull request by TRexStark**
_Please note that this PR does NOT include the latest one I submitted #16 . Please let me know if you want me to bundle them later_

**This PR adds additional UI functionality to the Radio List:**
- Ability to align the Radio List Horizontally
- Ability to position the label below, above, to the left or to the right (default) of the radio buttons
- Ability to display the Radio buttons as standard buttons in a similar fashion to Contentment's Button List. _(I remember seeing a request from someone either in Github or Discord but could not find it for reference - but I remember that Lee stated that his package works a bit differently hence it will be a bit complex to integrate)_ - this option resolves that issue by using some CSS trickery to achieve the same look and feel.

_Apologies about the JS file space removals, VS auto-formatting keeps kicking in with every change, I try to keep up with it but I forget when I'm on a roll_

### CODE REVIEW

**Comment by skartknet** [comment]
Nice one! 

Just one thing. It would be good if the buttons also can be positioned vertically. They should follow the normal radio behaviour, otherwise it gets confusing but we can aligned radios but not buttons.

**Comment by TRexStark** [comment]
Thanks @skartknet I had it that way initially but didn't look good, it took too much space realestate ... But, thinking about it now, you're right, there might be people who'd want that option. I'll fix it up and send another PR.

**Comment by skartknet** [comment]
thanks. you don't need to create a new PR. Just commit your changes to this PR's branch and it will get updated.

**Comment by TRexStark** [comment]
@skartknet
Done. I just pushed another commit that allows vertical alignment for buttons

**Comment by skartknet** [comment]
Thanks @TRexStark . It looks like the branch has some conflicts on the CSS. Do you think you can fix it?

**Comment by TRexStark** [comment]
I'll have a look @skartknet

**Comment by TRexStark** [comment]
@skartknet
Done

**Pull request merged**
